### ISSUE TITLE
Research Serialization

### ISSUE THREAD

**Issue by KeiranGlynn** [ByteClubGames/YumiAndTheYokai#81]
Please look into storing a game object's data using serialization. Make a test scene where a very simple game object with a few different data fields (some public, private, and serialized) can be deleted, re-instantiated, or loaded into a different scene while maintaining the data stored in its serialized fields.

**Comment by KeiranGlynn** [comment]
Kind of an abstract task, but I think having a serialization test scene will be great to reference when we get to other tasks that require serialization later on in this project.

**Comment by Evanito** [comment]
Will update.
Found several different methods:

- [Method] Keep a hidden game object consistent through scenes, attach scripts that manage player health, score, etc. Object must be in only one scene, as revisiting the scene it was initialized in will double it.
https://docs.unity3d.com/ScriptReference/Object.DontDestroyOnLoad.html

- [Note] Serialization as used in Unity is used more on the development side of the project and affects performance of scripts instead of logic. 
https://docs.unity3d.com/Manual/script-Serialization.html

- [Method] Serialized Objects (read more)
https://docs.unity3d.com/ScriptReference/SerializedObject.html

- [Method] Static public variables - cannot be attached to objects (read more)

**Comment by Evanito** [comment]
Relevant tutorial for our uses:
https://unity3d.com/learn/tutorials/topics/scripting/persistence-saving-and-loading-data
